'use strict';

export const ingredients = [
{name: "5 alpha Androstan 3 alpha ol 17 one"},
{name: "Dehydroepiandrosterone"},
{name: "7-KETO-DHEA"},
{name: "androstenolone"},
{name: "DHEA"},
{name: "Abuta"},
{name: "Vachellia rigidula"},
{name: "ACETYLCARNITINE, L-"},
{name: "acetyl-L-carnitine"},
{name: "Aconitum bisma"},
{name: "Aconite"},
{name: "Aconitus napellus"},
{name: "aconitum"},
{name: "Aconite napellus"},
{name: "Aconitum angustifolium Bernh. & Reichb"},
{name: "Activated carbon"},
{name: "Activated Charcoal"},
{name: "charcoal activated"},
{name: "Adénosine"},
{name: "Adenosine"},
{name: "Adenosine 5'-(trihydrogen diphosphate) P'-5'-ester with 3-(aminocarbonyl)-1-beta-D-ribofuranosylpyridinium inner salt"},
{name: "Adenosine cyclic-3',5'-(hydrophosphate)"},
{name: "Adenosine 5'-(tetrahydrogen triphosphate)"},
{name: "Adenosine 5'-(tetrahydrogen triphosphate), disodium salt"},
{name: "Adenosine 5'-(disodium triphosphate)"},
{name: "Adenosinum cyclophosphoricum"},
{name: "Adenosine 5'-triphosphoric acid"},
{name: "Blighia sapidas"},
{name: "Alder Buckthorn"},
{name: "Rhamnus frangula"},
{name: "Agar"},
{name: "agars"},
{name: "agave"},
{name: "Agrimonia (plant)"},
{name: "Agrimony"},
{name: "Ajuga nipponensis"},
{name: "Albizia Julibrissin"},
{name: "Albizia, NOS"},
{name: "Albizia"},
{name: "OH"},
{name: "Aletris farinosa"},
{name: "Aletris alba"},
{name: "Aletris"},
{name: "Alkanna Tausch"},
{name: "Allspice - dietary"},
{name: "Allspice"},
{name: "Aloe socotrina"},
{name: "Aloe vulgaris"},
{name: "Aloe"},
{name: "Aloe Vera"},
{name: "Aloe vera barbadensis"},
{name: "Aloe vera (L.) Burm. f. (Asphodelaceae/Aloaceae)"},
{name: "Hydroxy acids"},
{name: "Alpha Hydroxy Acids"},
{name: "alchemilla"},
{name: "L-Alanine"},
{name: "Beta-alanine"},
{name: "Alpha-Alanine"},
{name: "l alanine"},
{name: "acid alpha linolenic"},
{name: "Gamma Linolenic Acid"},
{name: "Alpha-Linolenic Acid"},
{name: "Calcium alpha-ketoglutarate"},
{name: "L-Arginine alpha-ketoglutarate"},
{name: "Glutamine alpha-ketoglutarate"},
{name: "L(+)-Ornithine alpha-ketoglutarate"},
{name: "Ornithine alpha-ketoglutarate"},
{name: "Ketoglutarate"},
{name: "Alpha-Ketoglutarate"},
{name: "alpha Ketoglutarate"},
{name: "Creatine-alpha-ketoglutarate"},
{name: "Ornithine Ketoglutarate"},
{name: "Amaranth"},
{name: "amaranth dye"},
{name: "alpinia"},
{name: "Chestnut, Dietary"},
{name: "Chestnut"},
{name: "White Chestnut"},
{name: "Sweet chestnut"},
{name: "Virginia Creeper"},
{name: "Ampelopsis quinquefolia"},
{name: "Asimina, NOS"},
{name: "American pawpaw"},
{name: "Hellebor nipper"},
{name: "helleborus"},
{name: "Helleborus niger"},
{name: "Andrachne"},
{name: "Aralia"},
{name: "Aralia quinquefolia"},
{name: "American Spikenard"},
{name: "Aralia (plant)"},
{name: "Spikenard"},
{name: "Andrographis Paniculata Extract"},
{name: "Andrographis"},
{name: "Andrographolide"},
{name: "Jamacian Dogwood"},
{name: "American Dogwood"},
{name: "dogwood"},
{name: "Androstenetriol (substance)"},
{name: "Nymphaea L., 1753"},
{name: "Nymphaea odorata"},
{name: "ninjin"},
{name: "American Ginseng"},
{name: "Angostura"},
{name: "Angelica sinensis-radix"},
{name: "Angelica"},
{name: "Angelica officinalis"},
{name: "Angelica sinensis"},
{name: "Angelica atropupurea"},
{name: "Radix Angelicae Sinensis"},
{name: "Annatto"},
{name: "Natural orange 4"},
{name: "antineoplaston A3"},
{name: "Antineoplastons"},
{name: "apoaequorin"},
{name: "maltoses"},
{name: "Maltose"},
{name: "Crystallin, NOS"},
{name: "4 Androstene 3,17 dione"},
{name: "Arabinoxylan rice bran"},
{name: "arabinoxylan"},
{name: "Arenaria <Caryophyllaceae>"},
{name: "Arnica"},
{name: "Apricot"},
{name: "American mistletoe"},
{name: "Arsenicum bromatum"},
{name: "Arsenicum album"},
{name: "Arsenicum sulphuratum rubrum"},
{name: "Arsenic"},
{name: "Arsenicum sulphuratum flavum"},
{name: "Arsenicum iodatum"},
{name: "ANDROSTENEDIOL"},
{name: "Artichoke"},
{name: "Anise"},
{name: "Arum maculatum"},
{name: "arum"},
{name: "Arum triphyllum"},
{name: "Umbrella Arum"},
{name: "Aristolochia clematitis"},
{name: "aristolochia"},
{name: "ascorbigen"},
{name: "Ferula assafoetida"},
{name: "Asafoetida"},
{name: "Asafetida (food)"},
{name: "Ashwagandha"},
{name: "Ashwagandha preparation"},
{name: "maranta"},
{name: "Asparagus racemosus"},
{name: "Chinese Asparagus"},
{name: "Asparagus"},
{name: "Asparagus Plants"},
{name: "Asparagus Officinalis"},
{name: "L-aspartic acid"},
{name: "L-aspartic acid, compound with L-lysine (1:1)"},
{name: "acid aspartic"},
{name: "D-Aspartic Acid"},
{name: "Atractylodes lancea"},
{name: "Atractylodes DC., 1838"},
{name: "Atractylodes"},
{name: "Rhizoma Atractylodis Macrocephalae"},
{name: "Astragalus Plants"},
{name: "Astragalus"},
{name: "Astragalus menziesii"},
{name: "Avens"},
{name: "Geum (plant)"},
{name: "Colchicum autumnales"},
{name: "Asarum, NOS"},
{name: "Avocado unsaponifiables"},
{name: "Avocado-Soybean unsaponifiables"},
{name: "Avocado"},
{name: "persea americana"},
{name: "Fraxinus"},
{name: "Ash"},
{name: "Fraxinus rhynchophylla"},
{name: "Northern Prickly Ash"},
{name: "Prickly Ash (Unspecified)"},
{name: "Ash tree"},
{name: "Fraxinus stylosa"},
{name: "Prickly Ash Bark"},
{name: "bee venom"},
{name: "bee pollen"},
{name: "BENZOIN RESIN"},
{name: "Styrax benzoin"},
{name: "benzoin tincture"},
{name: "Benzoinum"},
{name: "Benzoin"},
{name: "Belladonna"},
{name: "Belladonna-radix"},
{name: "Belladonna baccifera"},
{name: "MONARDA DIDYMA WHOLE"},
{name: "beta-glucan"},
{name: "(1-4)-2-Amino-2-deoxy-beta-D-glucan"},
{name: "Beta glucans"},
{name: "glucans"},
{name: "1,4-a-D-glucan glucanohydrolase"},
{name: "Oat Beta-glucan"},
{name: "(1,3)-beta-D-glucan"},
{name: "1,3-(1-3,1-4)-beta-D-glucan 3(4)-glucanohydrolase"},
{name: "3-(1-3,1-4)-beta-D-glucan 3(4)-glucanohydrolase"},
{name: "Chitin-glucan"},
{name: "Beta 1,3- 1,6 glucans"},
{name: "1,4-ß-D-glucan cellobiohydrolase"},
{name: "beta-1,3/1,6-D-Glucan"},
{name: "Beta-Glucanase"},
{name: "Beta-D-Fructofuranosyl-alpha-D-glucopyranoside"},
{name: "Beta-Sitosterolin-Beta-D-Glucoside"},
{name: "Beta-D-Fructofuranosidase"},
{name: "Beta (2-1) fructans"},
{name: "Beta rosa"},
{name: "Beta Sitosterol"},
{name: "Beta-aminopropionic acid"},
{name: "Hydroxypropyl Beta Cyclodextrin"},
{name: "Beta-Methylphenylethylamine"},
{name: "Beta plant"},
{name: "Beta-fructofuranosidase"},
{name: "Beta-hydroxy-beta-methylbutyrate monohydrate"},
{name: "Beta, epsilon-carotene-3,3'-diol"},
{name: "Beta-alanyl-L-histidine"},
{name: "Beta-hydroxy-beta-methylbutyrate"},
{name: "Beta-D-galactoside galactohydrolase"},
{name: "Beta-Hydroxy-Tyramine"},
{name: "Beta Phenethylalamine"},
{name: "Quebracho"},
{name: "Beta-Sitosterol"},
{name: "22,23-dihydrostigmasterol"},
{name: "(3B)-stigmast-5-en-3-ol"},
{name: "SITOSTEROL, BETA-"},
{name: "beta-Sitosterol-beta-D-glycoside"},
{name: "Berberine sulfate"},
{name: "Berberine"},
{name: "Amphetamine, NOS"},
{name: "BETAINE, ANHYDROUS"},
{name: "Betaine Anhydrous"},
{name: "Benzenemethanol, a-[1-(methylamino)ethyl]-, [S-(R*, R*)]-, hydrochloride. (+)-Pseudoephedrine hydrochloride"},
{name: "Dopamine hydrochloride"},
{name: "L-Glutamic acid hydrochloride"},
{name: "4-(2-Aminoethyl)imidazole dihydrochloride"},
{name: "Pseudoephedrine Hydrochloride"},
{name: "Acetyl L-Carnitine Hydrochloride"},
{name: "1H-Imidazole-4-ethanamine, dihydrochloride"},
{name: "Histamine hydrochloride"},
{name: "N,N-Dimethylglycine hydrochloride"},
{name: "L-Valine ethyl ester hydrochloride"},
{name: "Thiamine hydrochloride"},
{name: "2-Amino-2-deoxy-beta-D-glucopyranose hydrochloride"},
{name: "Glutamic acid hydrochloride"},
{name: "L-Leucine ethyl ester hydrochloride"},
{name: "2-Amino-2-deoxy-D-glucose hydrochloride"},
{name: "L-Isoleucine ethyl ester hydrochloride"},
{name: "(alphaS)-alpha-[(1S)-1-(Methylamino)ethyl]benzenemethanol hydrochloride"},
{name: "N-Acetyl L-carnitine hydrochloride"},
{name: "N-(3-Aminopropyl)-1,4-butanediamine trihydrochloride"},
{name: "L-arginine hydrochloride"},
{name: "Lysozyme hydrochloride"},
{name: "Trimethylglycine hydrochloride"},
{name: "Ephedrine hydrochloride"},
{name: "(1S, 2S)-2-Methylamino-1-phenylpropan-1-ol hydrochloride"},
{name: "d-pseudoephedrine hydrochloride"},
{name: "Betaine Hydrochloride"},
{name: "Histamine Dihydrochloride"},
{name: "L-ornithine hydrochloride"},
{name: "hydrochloride"},
{name: "Creatine ethyl ester hydrochloride"},
{name: "Glucosamine hydrochloride"},
{name: "Glycine propionyl L-carnitine hydrochloride"},
{name: "Betaine"},
{name: "Glycine betaine"},
{name: "Trimethylglycine"},
{name: "Glycine-betaine"},
{name: "Trimethylglycine anhydrous"},
{name: "Beers"},
{name: "Birch"},
{name: "Birch antigen"},
{name: "Bismuth"},
{name: "Bismuthum Oxydatum"},
{name: "Bismuthum subnitricum"},
{name: "Bismuthum metallicum"},
{name: "Almond"},
{name: "Bitter Almond"},
{name: "Momordica charantia"},
{name: "charantia momordica"},
{name: "Bitter Melon"},
{name: "Milkwort"},
{name: "Genus Dioscorea"},
{name: "Rhizoma dioscoreae"},
{name: "Dioscorea Composita"},
{name: "Rhizoma Dioscoreae Spongiosae"},
{name: "Dioscorea hypoglauca"},
{name: "Bittersweet"},
{name: "celastrus"},
{name: "genus Solanum"},
{name: "Black alder"},
{name: "Bistort"},
{name: "Black Cohosh"},
{name: "cimicifuga racemosa"},
{name: "Biotin"},
{name: "Biotine"},
{name: "Bryony, Black"},
{name: "Mustard (unspecified)"},
{name: "Mustard preparation"},
{name: "Black Mustard"},
{name: "Black Mulberry"},
{name: "Mulberry (food)"},
{name: "Black Pepper and White Pepper"},
{name: "Black Pepper"},
{name: "Solanum dulcamara"},
{name: "Solanum lycopersicum"},
{name: "solanum nigrum"},
{name: "Solanum lycopersicum var. lycopersicum"},
{name: "Horehound, Black"},
{name: "Raspberry"},
{name: "Black Raspberry"},
{name: "Raspberry extract"},
{name: "Red Raspberry"},
{name: "Raspberry Ketones"},
{name: "Semen Oryzae"},
{name: "Black Seed"},
{name: "Coffea arabica seed extract"},
{name: "Cannabis Sativa seed"},
{name: "plant seeds"},
{name: "Peony seeds"},
{name: "Grape Seed"},
{name: "Plukenetia volubilis seed protein"},
{name: "Semen hordei vulgaris germinatum"},
{name: "Oryza sativa (Rice) Seed Protein"},
{name: "Grape seed extract"},
{name: "Sweet almond seed extract"},
{name: "Grape seed Extract-Phosphatidylcholine Complex"},
{name: "Semen sojae germinatum"},
{name: "Semen Pharbitidis"},
{name: "Semen Coicis"},
{name: "Hemp Seed Protein"},
{name: "Grape seed Oligomeric proanthocyanidins-Phosphatidylcholine complex"},
{name: "Semen Cuscutae chinensis"},
{name: "Hemp Seed"},
{name: "Black Walnut"},
{name: "juglans nigra"},
{name: "Radix Stemonae"},
{name: "Radix et Rhizoma Rhei"},
{name: "Radix Polygalae Tenuifoliae"},
{name: "Radix Platicodonis"},
{name: "Pleurisy root"},
{name: "Baical skullcap root"},
{name: "Radix rehmanniae preparata"},
{name: "Radix Glycyrrhizae Preparata"},
{name: "Radix Codonopsis Pilosula"},
{name: "Clove Root"},
{name: "Pink Root"},
{name: "Gang mei root"},
{name: "Radix Adenophorae"},
{name: "Radix Platycodi Gradiflori"},
{name: "Gravel root"},
{name: "Isatis root"},
{name: "Black root"},
{name: "Bitter Evodia Root"},
{name: "Plant roots"},
{name: "Licorice root"},
{name: "Radix Scrophulariae"},
{name: "Elecampane root"},
{name: "Radix Aucklandiae"},
{name: "Radix Scutellariae"},
{name: "Eleuthero Root"},
{name: "Gentian Root"},
{name: "Nerve Root"},
{name: "Radix Glycyrrhizae Uralensis"},
{name: "Radix curcumae"},
{name: "Radix et Rhizoma Gentianae"},
{name: "Radix Glycyrrhizae"},
{name: "Stone Root"},
{name: "Druparia spinosa"},
{name: "Prunus spinosa"},
{name: "cnicus"},
{name: "Blessed Thistle"},
{name: "bilberry extract"},
{name: "Bilberry Fruit"},
{name: "bilberry"},
{name: "Sanguinaria canadenses"},
{name: "Bloodroot"},
{name: "Caulophyllum thalictroides"},
{name: "Caulophyllum thalictroide"},
{name: "Blue Cohosh"},
{name: "Blue-Green Algae"},
{name: "Cyanobacterium"},
{name: "rose oil"},
{name: "Boldea fragrans"},
{name: "peumus boldus"},
{name: "Boldo"},
{name: "Blueberry"},
{name: "borago"},
{name: "Borage"},
{name: "Borago officinalis"},
{name: "eupatorium perfoliatum"},
{name: "Boneset"},
{name: "Boron"},
{name: "Boron Hydrolyzed Vegetable Protein"},
{name: "Bovine Colostrum"},
{name: "Colostrum"},
{name: "Colostrum Preparation"},
{name: "Breadfruits"},
{name: "Butanoic acid"},
{name: "2-Hydroxybenzoic Acid"},
{name: "cis-9,trans-11 Conjugated linoleic acid"},
{name: "2-Oxo-1,5-pentanedioic acid"},
{name: "Malic Acid"},
{name: "Acetic acid, calcium salt, monohydrate"},
{name: "L-alpha-aminoisovaleric acid"},
{name: "L-2-amino-3-mercaptopropanoic acid"},
{name: "L-2-amino-4-methylvaleric acid"},
{name: "alpha Methyl Tetradecylthioacetic Acid"},
{name: "[R-(R*,S*)]-2-amino-3-hydroxybutanoic acid"},
{name: "2-[[(3alpha,5beta,7beta)-3,7-Dihydroxy-24-oxocholan-24-yl]amino]ethanesulfonic acid"},
{name: "5-[(3-R)-dithiolan-3-yl)]pentanoic acid"},
{name: "L-alpha-Acetamido-beta-mercaptopropionic acid"},
{name: "(S)-2-pyrrolidinecarboxylic acid"},
{name: "2-Amino-3-phenyl-propanoic acid"},
{name: "(S)-2-aminopropanoic acid"},
{name: "(S)-alpha-Amino-4-hydroxybenzenepropanoic acid"},
{name: "(2S)-2-Hydroxybutanedioic acid"},
{name: "Aminoisovalerie acid"},
{name: "10-Undecenoic acid"},
{name: "Nitric acid sodium salt (1:1)"},
{name: "Cis-9,cis-12,cis-15-Octadecatrienoic acid"},
{name: "1,2,3-Propanetricarboxylic acid, 2-hydroxy-, zinc salt, hydrate (2:3:3)"},
{name: "(all-Z)-5,8,11,14,17-Eicosapentaenoic acid"},
{name: "(S)-2-Amino-3-phenylpropanoic acid"},
{name: "1,2-dithiolane-3-pentanoic acid"},
{name: "(3alpha,14beta,16alpha)-14,15-Dihydro-14-hydroxyeburnamenine-14-carboxylic acid methyl ester"},
{name: "(S)-alpha-amino-1H-imidazole-4-propanoic acid"},
{name: "5-(1,2-dithiolan-3-yl)pentanoic acid"},
{name: "Acid, NOS"},
{name: "Humic acids"},
{name: "Dehydrochloric Acid"},
{name: "Calcium/Potassium Salt of Hydroxycitric Acid"},
{name: "3-alpha,16-alpha-Apovincaminic acid ethyl ester"},
{name: "(2S)-2-amino-4-carbamoyl-butanoic acid"},
{name: "9-Tetradecenoic acid, hexadecyl ester,(Z)-"},
{name: "L-alpha-Aminoindole-3-propionic acid"},
{name: "Diphosphoric acid, tetrasodium salt"},
{name: "(2S,3S)-2-Amino-3-methylpentanoic acid"},
{name: "2(s)-2,6-Diaminohexanoic acid"},
{name: "Acid casein"},
{name: "3-Pyridinecarboxylic acid methyl ester"},
{name: "Selenium amino acid chelate"},
{name: "Behenic Acid"},
{name: "Branched Chain Amino Acids"},
{name: "2-amino-4-methyl pentanoic acid"},
{name: "(2R)-2-aminobutanedioic acid"},
{name: "2-amino-3-methyl pentanoic acid"},
{name: "2-(carbamimidoyl-methyl-amino) ethoxyphosphonic acid"},
{name: "(6S)-5-Methyltetrahydrofolic acid, glucosamine salt"},
{name: "(S)-2-Amino-3-methylbutanoic acid"},
{name: "(S)-Aminobutanedioic acid"},
{name: "(5Z,8Z,11Z,14Z)-5,8,11,14-Eicosatetraenoic acid"},
{name: "Oleanolic acid"},
{name: "10-Undecenoic acid, zinc salt"},
{name: "(E)-4'-Hydroxy-3'-methoxycinnamic acid"},
{name: "Acid-stable protease"},
{name: "1H-Pyrrolo(2,3-f)quinoline-2,7,9-tricarboxylic acid, 4,5-dihydro-4,5-dioxo-"},
{name: "Rosmarinic Acid"},
{name: "Guanidinopropionic acid"},
{name: "Conjugated Linoleic Acid"},
{name: "Ellagic acid"},
{name: "2-Hydroxypropane-1,2,3-tricarboxylic acid"},
{name: "L- 2,6- diaminohexanoic acid"},
{name: "Lactic Acid"},
{name: "Phosphoric acid, monosodium salt, monohydrate"},
{name: "3-amino-1-propanesulfonic acid"},
{name: "1, 2-dithiolane-3R, S-pentanoic acid"},
{name: "Chromium amino acid chelate"},
{name: "Hexahydro-2-oxo-1H-thieno[3,4-d]imidazole-4-pentanoic acid"},
{name: "Undec-10-enoic acid, C11H20O2"},
{name: "L-2-Amino-5-guanidinopentanoic acid"},
{name: "2-hydroxy-1,2,3-propanetricarboxylic acid zinc salt"},
{name: "Nitric acid silver(1+) salt (1:1)"},
{name: "Benzenecarbothioic acid S-[2-[[(4-amino-2-methyl-5-pyrimidinyl)methyl]formylamino]-1-[2-(phosphonooxy)ethyl]-1-propenyl] ester"},
{name: "(S)-2-amino-4-methylpentanoic acid"},
{name: "L-2-Aminoglutaramic acid"},
{name: "1,2,3,4,5,6-Cyclohexanehexolphosphoric acid"},
{name: "Nitric acid calcium salt (2:1)"},
{name: "3-O-Methylcaffeic acid"},
{name: "2-hydroxy-1,2,3-propanetricarboxylic acid calcium salt (2:3)"},
{name: "2-Hydroxy-1,2,3-propanetricarboxylic acid magnesium salt"},
{name: "Carbonic acid potassium salt (1:1)"},
{name: "Acetic acid"},
{name: "Phosphoric acid, disodium salt"},
{name: "Kojic acid"},
{name: "(S)-2-Aminopentanedioic acid"},
{name: "L-2-amino-3-methylvaleric acid"},
{name: "(2R)-2-Hydroxypropanoic acid"},
{name: "(S)-alpha,delta-Diaminovaleric acid"},
{name: "2-amino-3-indolylpropanoic acid"},
{name: "2-amino-3-methyl butanoic acid"},
{name: "3-Hydroxy-3-Methylbutyric Acid"},
{name: "2-amino-3-mercaptopropanoic acid"},
{name: "3-Aminopropanoic acid"},
{name: "Carbonic acid calcium salt (1:1)"},
{name: "(S)-2-Amino-5-((aminoiminomethyl)amino)pentanoic acid"},
{name: "(S)-2-Amino-5-[(aminoiminomethyl)amino]pentanoic acid"},
{name: "Alpha-aminohydrocinnamic acid"},
{name: "Carbonic acid, magnesium salt (1:1)"},
{name: "Caprylic Acid"},
{name: "[2S-(2alpha,3E,4beta)]-3-Ethylidene-2-(beta-D-glucopyranosyloxy)-3,4-dihydro-5-(methoxycarbonyl)-2H-pyran-4-acetic acid 2-(3,4-dihydroxyphenyl)ethyl ester"},
{name: "Hexadecenoic Acid"},
{name: "3-Aminopropionic acid"},
{name: "2-Aminoethanesulfonic acid"},
{name: "3,3'-(1,3-Dioxo-1,3-digermoxanediyl)bispropanioic acid"},
{name: "(S)-2-amino-4-(methylthio)butanoic acid"},
{name: "Benzoic Acid"},
{name: "Alpha-Ketoglutaric acid"},
{name: "Sodium salt of Carbonic Acid"},
{name: "(3-beta)-3-Hydroxyolean-12-en-28-oic acid"},
{name: "(3, 16)-Eburnamenin-14-carboxylic acid ethyl ester"},
{name: "2-hydroxy-1,2,3-propanetricarboxylic acid"},
{name: "(2R)-2-amino-4-methyl-pentanoic acid"},
{name: "2-Hydroxypropane-1,2,3-tricarboxylic acid monohydrate"},
{name: "L-(+)-2-Aminoglutaramic acid"},
{name: "Nitric acid sodium salt"},
{name: "Phosphorofluoridic acid, disodium salt"},
{name: "(S)-2,5-Diamino-5-oxopentanoic acid"},
{name: "4,4prime,5,5prime,6,6prime-hexa hydrodiphenic acid 2,6,2prime,6prime-dilactone"},
{name: "2-acetylamino-3-(4-hydroxyphenyl)-propanoic acid"},
{name: "1,2-Dithiolane-3-pentanoic acid, (R)"},
{name: "Galactoarabinan polyglucoronic acid cross polymer"},
{name: "Silicic acid, magnesium salt (1:2)"},
{name: "Glutamic Acid"},
{name: "1,2,3-Propanetricarboxylic acid, 2-hydroxy-, calcium salt (2:3)"},
{name: "Eicosapentaenoic acid"},
{name: "2-hydroxybenzoic acid methyl ester"},
{name: "L-Glutamine or 2 - aminoglutaramic acid"},
{name: "(+)-1,2-dithiolane-3-pentanoic acid"},
{name: "3-carboxy-2-hydroxy-N,N,N-trimethyl-(2R)-1-propanaminium, 2:1 salt with (2R,3R)-2,3-dihydroxybutanedioic acid"},
{name: "Alpha-ketoisocaproic acid calcium salt"},
{name: "(S)-2,5-Diaminopentanoic acid"},
{name: "1H-Pyrrolo(2,3-f)quinoline-2,7,9-tricarboxylic acid, 4,5-dihydro-4,5-dioxo, disodium salt"},
{name: "(2S)-2-Amino-5-{[amino(imino)methyl]amino}pentanoic acid"},
{name: "Diiodothyroacetic Acid"},
{name: "1,2-dithiolane-3R, S-pentanoic acid"},
{name: "Fluoric acid"},
{name: "(3alpha,5beta,12alpha)-3,12-Dihydroxy-5-cholan-24-oic acid"},
{name: "Thiobenzoic acid S-ester with N-[(4-amino-2-methyl-5-pyrimidinyl)methyl]-N-(4-hydroxy-2-mercapto-1-methyl-1-butenyl)formamide O-phosphate"},
{name: "(R)-1,2-dithiolane-3-pentanoic acid"},
{name: "L-2-amino-4-methylpentanoic acid"},
{name: "1H-Pyrrolo(2,3-f)quinoline-2,7,9-tricarboxylic acid, 4,5-dihydro-4,5-dioxo-, disodium salt"},
{name: "(3alpha,16alpha)-Eburnamenine-14-carboxylic acid ethyl ester"},
{name: "(2S,3R)-2-Amino-3-hydroxybutyric acid"},
{name: "Oleic acid"},
{name: "2-Keto-4-methyl-pentanoic acid"},
{name: "Monounsaturated fatty acids"},
{name: "2-Aminoethylsulfonic acid"},
{name: "(Z)-9-Octadecenoic acid"},
{name: "1,2-dithiolane-3R-pentanoic acid"},
{name: "Indian Frankincense Boswellic acids-Phosphatidylcholine complex"},
{name: "L-2-amino-4-(methylthio)butanoic acid"},
{name: "L-alpha-amino-sovaleric acid"},
{name: "Humic acid"},
{name: "L-alpha-amino-beta-methylvaleric acid"},
{name: "Phosphoric acid"},
{name: "L-5-Methyltetrahydrofolic acid, calcium salt"},
{name: "(±)-1,2-Dithiolane-3-pentanoic acid"},
{name: "2-Hydroxy-1,2,3-propanetricarboxylic acid tripotassium salt"},
{name: "Branched-Chain Amnio Acids"},
{name: "para-Aminobenzoic Acid"},
{name: "10-Undecenoic acid, calcium(2+) salt"},
{name: "Phosphoric acid, disodium salt, heptahydrate"},
{name: "(+-)-1,2-Dithiolane-3-pentanoic acid"},
{name: "Nitric acid potassium salt (1:1)"},
{name: "Fulvic Acid"},
{name: "L-gamma-methylthio-alpha-aminobutyric acid"},
{name: "L-2-amino-3-mercaptopropionic acid"},
{name: "L-alpha-amino-beta-hydroxdypropionic acid"},
{name: "Benzoic acid, 2-hydroxy-, methyl ester"},
{name: "2-Hydroxy-4-methylpentanoic acid"},
{name: "(2S)-2-Aminoglutaramic acid"},
{name: "(4Z,7Z,10Z,13Z,16Z,19Z)-4,7,10,13,16,19-Docosahexaenoic acid"},
{name: "(Z)-octadec-9-enoic acid"},
{name: "L-2-amino-3-methylbutyric acid"},
{name: "2-Amino-2,3,5-trideoxy-3-methyl-L-ribonic acid"},
{name: "Carbonic acid calcium salt"},
{name: "3-carboxy-3-oxopropanoic acid"},
{name: "2-Hydroxy-1,2,3-propanetricarboxylic acid sodium salt (1:3)"},
{name: "Linoleic Acid"},
{name: "(S)-2,6-Diaminohexanoic acid"},
{name: "(2S)-2-Aminopentanedioic acid"},
{name: "D(-)-lactic acid"},
{name: "(R)-Aminobutanedioic acid"},
{name: "2-amino-3-hydroxypropionic acid"},
{name: "4-Hydroxybenzoic acid, methyl ester"},
{name: "Cetylated fatty acids"},
{name: "2-Hydroxy-2-methylacetic acid"},
{name: "Guanidinopropionic Acid (GPA )"},
{name: "(2R,3R)-2,3-Dihydroxybutanedioic acid potassium salt (1:1)"},
{name: "(R)-dithiolane-3-pentanoic acid"},
{name: "Carbonic acid sodium salt (1:1)"},
{name: "(Z,Z,)-9,12-Octadecadienoic acid"},
{name: "Acetic acid, zinc salt"},
{name: "2-Oxopropanoic acid"},
{name: "gluconate / gluconic acid"},
{name: "1,2,3-Propanetricarboxylic acid, 2-hydroxy-, monohydrate"},
{name: "Citric acid"},
{name: "Ethanaminium, 2-hydroxy-N,N,N-trimethyl-, salt with 2-hydroxy-1,2,3-propanetricarboxylic acid (1:1)"},
{name: "Carbonic acid, diammonium salt"},
{name: "(R)-5-(1,2-dithiolan-3-yl)pentanoic acid"},
{name: "1,2-Dihydroxy-1,2,3-propanetricarboxylic acid"},
{name: "(S)-2-aminopropionic acid"},
{name: "2-amino-3-(4-hydroxyphenyl)propionic acid"},
{name: "Alpha-ketoisocaproic acid"},
{name: "2,5-diaminopentanoic acid"},
{name: "Salicylic acid"},
{name: "Orotic acid"},
{name: "1,2,3-Propanetricarboxylic acid, 2-hydroxy-, disodium salt"},
{name: "Benzenecarboxylic acid"},
{name: "L-2-amino-3-methylbutanoic acid"},
{name: "2-Oxobutanedioic acid"},
{name: "Peptide Bonded Amino Acids"},
{name: "cis-6,cis-9,cis-12-Octadecatrienoic acid"},
{name: "(2S)-2,6-Diaminohexanoic acid monohydrochloride"},
{name: "(S)-2-Amino-3-hydroxypropanoic acid"},
{name: "3-Pyridinecarboxylic acid"},
{name: "Nitric acid"},
{name: "3beta-Hydroxy-11-oxoolean-12-en-30-oic acid"},
{name: "1,2,3-Propanetricarboxylic acid, 2-hydroxy-, trisodium salt, dihydrate"},
{name: "2-Hydroxy-4-methylvaleric acid"},
{name: "1,2-dithiolane-3-valeric acid"},
{name: "1,2,3-Propanetricarboxylic acid, 2-hydroxy-, calcium salt"},
{name: "(2S,3R)-2-amino-3-hydroxybutanoic acid"},
{name: "(z,z,z) octadeca-6, 9, 12 trienoic acid"},
{name: "(4S)-1,4,5,6-Tetrahydro-2-methyl-4-pyrimidinecarboxylic acid"},
{name: "Hydrofluoric acid"},
{name: "2-aminopentanedioic acid"},
{name: "(R)-2-Amino-3-mercaptopropanoic acid"},
{name: "(2S)-2,6-Diaminohexanoic acid"},
{name: "Humic acids, potassium salts"},
{name: "(3alpha,5beta,6alpha)-3,6-dihydroxycholan-24-oic acid"},
{name: "(6Z,9Z,12Z)-6,9,12-Octadecatrienoic acid"},
{name: "Oxalic acid"},
{name: "Hydroxybutanedioic acid"},
{name: "Green lipped mussel fatty acids"},
{name: "Docosapentaenoic acid"},
{name: "2,3 dihydroxybutanedioic acid"},
{name: "Carbonic acid, zinc salt (1:1)"},
{name: "Boronic acid analogues"},
{name: "Gamma linoleic acid"},
{name: "Buxus, NOS"},
{name: "Brickellia"},
{name: "Betel nut"},
{name: "Areca catechu"},
{name: "Broccoli Sprouts"},
{name: "Broccoli"},
{name: "brassica oleracea"},
{name: "Psyllium preparation"},
{name: "Blond Psyllium"},
{name: "Psyllium"},
{name: "Psyllium (not specified)"},
{name: "Brewer's Yeast"},
{name: "Saccharomyces Cerevisiae"},
{name: "Torula cerevisiae"},
{name: "veratrum"},
{name: "Veratrum viride"},
{name: "Utricularia caerulea"},
{name: "bovine cartilage"},
{name: "bovine cartilage / glycosaminoglycan"},
{name: "Buchu"},
{name: "Buchu Leaf Extract"},
{name: "Buckhorn Plantain"},
{name: "Water Plantain"},
{name: "plantain antigen"},
{name: "Plantain"},
{name: "Great Plantain"},
{name: "Ajuga"},
{name: "lycopus"},
{name: "bugleweed"},
{name: "Buckwheat"},
{name: "Polygonum fagopyrum"},
{name: "FAGOPYRUM ESCULENTUM"},
{name: "Bupleurum"},
{name: "ranunculus"},
{name: "BUTYLENE GLYCOL"},
{name: "Burr - plant"},
{name: "Buteas"},
{name: "Butterbur"},
{name: "Tussilago petasites"},
{name: "petasites"},
{name: "Hydroxytoluene, Butylated"},
{name: "Butternut"},
{name: "Butternut Squash"},
{name: "Juglans cinerea nut"},
{name: "Caffeic acid"},
{name: "Caffeic acid 3-methyl ether"},
{name: "Oil of cajuput"},
{name: "Cajuput Oil"},
{name: "Physostigma venenosums"},
{name: "Physostigma venenosum"},
{name: "Caffeine anhydrous"},
{name: "1,3,7-Trimethylxanthine"},
{name: "Caffeine"},
{name: "7-Methyltheophylline"},
{name: "Caffeine, NOS"},
{name: "3,7-Dihydro-1,3,7-trimethyl-1H-purine-2,6-dione"},
{name: "Caffeinum"},
{name: "Caffeine isolate"},
{name: "Anhydrous Caffeine"},
{name: "1,3,7-trimethylpurine-2,6-dionehydrate"},
{name: "Calamus perciform"},
{name: "Calamintha"},
{name: "Bridelia"},
{name: "Calea"},
{name: "Calcium Glucarate"},
{name: "juniperus oxycedrus"},
{name: "Marigold (unspecified)"},
{name: "Calendula"},
{name: "Calendula officinalis"},
{name: "Marigold Extract"},
{name: "Maize"},
{name: "Organic Purple Kculli Corn Extract"},
{name: "Starch - Maize"},
{name: "Waxy maize starch"},
{name: "zea mays"},
{name: "Waxy Maize"},
{name: "calotropis"},
{name: "Eschscholzia californica"},
{name: "Eschscholzia californicas"},
{name: "erigeron"},
{name: "Canada balsam extract"},
{name: "Canaigre"},
{name: "Hemp Protein Isolate"},
{name: "Hemp"},
{name: "Hemp Protein"},
{name: "Hemp antigen"},
{name: "Hemp Protein Concentrate"},
{name: "d-Camphor"},
{name: "Bicyclo(2.2.1)heptan-2-one, 1,7,7-trimethyl-, (1S,4S)-"},
{name: "Camphor"},
{name: "dl-Camphor"},
{name: "CAMPHOR, (+/-)-"},
{name: "Canella"},
{name: "cananga oil"},
{name: "Caper"},
{name: "Capsicum"},
{name: "Oleoresin of Capsicum"},
{name: "Capsicum Annuum"},
{name: "Capsicum grossum"},
{name: "Chili Pepper (dietary)"},
{name: "CANTHAXANTHIN"},
{name: "3,3'-Dihydroxy-beta,beta-carotene-4,4'-dione"},
{name: "Caraways"},
{name: "Bryonia"},
{name: "Bryonia, NOS"},
{name: "Burdock"},
{name: "Arctium (plant)"},
{name: "Arctium Lappa"},
{name: "Arctium pubens"},
{name: "Caralluma fimbriata"},
{name: "Caralluma R.Br."},
{name: "Calcium pangamate"},
{name: "Calcium sodium caseinate"},
{name: "Calcium D-saccharate"},
{name: "Calcium"},
{name: "Calcium sulfuricum"},
{name: "Calcium fructoborate"},
{name: "Calcium phosphate"},
{name: "Calcium L-5-methyltetrahydrofolate"},
{name: "Calcium Pyruvate"},
{name: "Calcium Chloride"},
{name: "Calcium Bisglycinate"},
{name: "Calcium jodatum"},
{name: "Calcium carbonicum Hahnemanni"},
{name: "Calcium fluoratum"},
{name: "Calcium 2-oxopropanoate"},
{name: "Calcium HVP chelate"},
{name: "Calcium sennosides"},
{name: "Calcium Magnesium Carbonate"},
{name: "Calcium Hydrogen Phosphate, Anhydrous"},
{name: "Calcium d-glucarate"},
{name: "Calcium sodium phosphosilicate"},
{name: "Calcium beta-hydroxy-beta-methylbutyrate"},
{name: "Calcium Caseinate"},
{name: "Calcium phosphate hydroxide"},
{name: "Calcium di(octanoate)"},
{name: "Calcium phosphoricum"},
{name: "Calcium iodatum"},
{name: "Calcium 4-methyl-2-oxovalerate"},
{name: "Calcium-potassium salt of (-)-hydroxycitric acid"},
{name: "Coral Calcium"},
{name: "Calcium hypochlorite"},
{name: "elettaria cardamomum"},
{name: "Amomum cardamomum"},
{name: "cannabidiol"},
{name: "Ricinus communis"},
{name: "Castor Bean"},
{name: "Castoreum"},
{name: "Cat's Claw Herbal Extract"},
{name: "Cat's Claw"},
{name: "Cat hair antigen"},
{name: "catechins"},
{name: "Cauliflower (dietary)"},
{name: "Nepeta catarias"},
{name: "Cereus <cactus>"},
{name: "Cereus bonplandii"},
{name: "Cereus serpentinus"},
{name: "Cesium Chloride"},
{name: "CESIUM"},
{name: "Omega-3 Fatty Acids"},
{name: "Fatty acids"},
{name: "Fatty acid, NOS"},
{name: "Omega-6 Fatty Acids"},
{name: "Apium graveolens var. dulce"},
{name: "Celery, Wild"},
{name: "oil of Chenopodium"},
{name: "kalmia"},
{name: "Water"},
{name: "Water Specimen"},
{name: "Chia"},
{name: "SH Seed"},
{name: "Rosehips"},
{name: "Dietary Chicory"},
{name: "Genus Cucumis"},
{name: "Cucumis pepo"},
{name: "Sea Cucumber"},
{name: "Aethiops mineralis"},
{name: "minerals"},
{name: "Reduced minerals whey"},
{name: "SierrasSil® Mineral complex"},
{name: "Silicate mineral complex"},
{name: "Carbo mineralis"},
{name: "Trace minerals"},
{name: "Ocean Mineral Concentrate"},
{name: "Aethiops mercurialis-mineralis"},
{name: "Ionic Trace Minerals"},
{name: "Whey mineral concentrate"},
{name: "Amino Acid Chelate"},
{name: "agents chelating"},
{name: "stellaria media"},
{name: "cascara sagrada"},
{name: "chitosan"},
{name: "Chlorella vulgaris"},
{name: "Chlorella <unclassified Chlorophyceae>"},
{name: "Chlorella Pyrenoidosa Extract"},
{name: "Chlorella vulgaris Beyerinck"},
{name: "Chlorella"},
{name: "Chlorophyllin (substance)"},
{name: "Chlorophyllin Copper Complex"},
{name: "Copper sodium chlorophyllin"},
{name: "Choline"},
{name: "Trimethylethanolamine"},
{name: "cholines"},
{name: "Choline cytidine 5'-pyrophosphate (ester)"},
{name: "2-Hydroxyethyltrimethylammonium hydrogen tartrate"},
{name: "chlorophylls"},
{name: "Chlorophyll"},
{name: "Sodium-copper salts of chlorophyll"},
{name: "chrysanthemum"},
{name: "Chrysanthemum indicum"},
{name: "Flos chrysanthemi"},
{name: "Flos Chrysanthemi morifolii"},
{name: "CHRYSIN"},
{name: "5,7-Dihydroxyflavone"},
{name: "Carlina"},
{name: "Chromium oxydatum"},
{name: "Chromium product (pharmacologic preparation)"},
{name: "Chromium kali sulphuricum"},
{name: "Chromium"},
{name: "Chromium sulphuricum"},
{name: "Aluminum potassium sulfate"},
{name: "Sodium Lauryl Ether Sulphate"},
{name: "Ferrous sulfate"},
{name: "Sulfate"},
{name: "2-Amino-2-deoxy-beta-D-glucose sulphate"},
{name: "Guanidine, (4-aminobutyl)-, sulfate (1:1)"},
{name: "Potassium sulfate"},
{name: "Oxovanadium(2+) sulfate"},
{name: "(4-Aminobutyl)guanidinium sulphate"},
{name: "Agmatine sulfate"},
{name: "Inorganic Sulfate"},
{name: "2-Amino-2-deoxy-D-glucose sulfate"},
{name: "2-Amino-2-deoxy-beta-D-glucopyranose sulfate"},
{name: "Anhydrous Ferrous Sulfate"},
{name: "S-Adenosyl-L-Methionine-Tosylate Disulfate"},
{name: "Sodium Sulphate Anhydrous"},
{name: "Sulfate De Chondroïtine"},
{name: "Vanadium oxide sulphate"},
{name: "Chondroitin sulfate"},
{name: "Ferric sulfate"},
{name: "5,6-Dihydro-9,10-dimethoxybenzo(g)-1,3-benzodioxolo(5,6-a)quinolizinium sulfate"},
{name: "D-Glucosamine sulphate"},
{name: "Magnesium sulfate"},
{name: "Dried Ferrous sulfate powder"},
{name: "hydrogen sulfate"},
{name: "Chondroitin"},
{name: "chondroitins"},
{name: "Sage"},
{name: "Diviner's Sage"},
{name: "Chaparral extract"},
{name: "Chaparral"},
{name: "Chives (dietary)"},
{name: "Cissus L., 1753"},
{name: "Cissus Quadrangularis"},
{name: "Chymotrypsin A and B"},
{name: "Chymotrypsin"},
{name: "alpha-Chymotrypsin"},
{name: "Cinchona Calisaya"},
{name: "Cinchona (plant)"},
{name: "Cinchonae ssp. (pubescens, calisaya, ledgeriana)"},
{name: "Cinchona officinalis"},
{name: "Cinchona succirubra"},
{name: "citicholine"},
{name: "Cytidine 5'-diphosphocholine"},
{name: "ciguatoxin"},
{name: "Cinnamomum camphora"},
{name: "Cinnamomum"},
{name: "Cinnamomum camphora (cineol chemotype)"},
{name: "Cinnamomum Schaeff., 1760"},
{name: "Cinnamomum aromaticum"},
{name: "Burmannia"},
{name: "Clove"},
{name: "Essential oil of clove"},
{name: "Clove Flower Oil"},
{name: "Clove essential oil"},
{name: "Oil of clove"},
{name: "Clematis Armandii"},
{name: "clematis"},
{name: "Clematis vitalba"},
{name: "Clematis Recta"},
{name: "Clematis vitalba-folia"},
{name: "Clematis erecta"},
{name: "Lycopodiaceae P.Beauv. ex Mirb., 1802"},
{name: "Cocillana"},
{name: "Cocillana extract"},
{name: "Cocillana composée"},
{name: "Citronella oil (substance)"},
{name: "cilantro"},
{name: "Coconut oil"},
{name: "(-)-cocaine"},
{name: "Cod liver oil"},
{name: "cod-liver oil"},
{name: "Codonopsis tangshen"},
{name: "Codonopsis"},
{name: "Codonopsis (plant)"},
{name: "Charcoal [Chemical/Ingredient]"},
{name: "Coenzyme Q10"},
{name: "Coenzyme A"},
{name: "Coenzyme"},
{name: "Coenzyme Q10, ubidecarenone"},
{name: "Cola Acuminata"},
{name: "Cola antigen"},
{name: "Nux moschata"},
{name: "Malabar Nut"},
{name: "Tree Nut"},
{name: "Colloidal Silver"},
{name: "Silver"},
{name: "Silver (usp)"},
{name: "Silver Diamine Fluoride"},
{name: "Chicken Type II Collagen"},
{name: "type ii collagen"},
{name: "Hydrolyzed Chicken Collagen Type II"},
{name: "Collagen type II"},
{name: "Hydrolyzed Collagen Type II"},
{name: "Cocoa Extract"},
{name: "Cnidium monnierie"},
{name: "cnidium"},
{name: "Cnidium monnieri"},
{name: "coleus"},
{name: "Columbine"},
{name: "Aquilegia vulgaris"},
{name: "Tussilago farfara"},
{name: "Copahu Balsam Resin"},
{name: "Copper HVP chelate"},
{name: "Copper"},
{name: "Coriolus Versicolor"},
{name: "Coriolus"},
{name: "Mushroom, NOS"},
{name: "Reishi Mushroom"},
{name: "Maitake Mushroom"},
{name: "Poria Mushrooms"},
{name: "Chaga Mushroom"},
{name: "Mushrooms"},
{name: "Poria Mushroom"},
{name: "Immunostimulating conjugate (antigen)"},
{name: "Marsdenia condurango"},
{name: "Gonolobus condurango"},
{name: "Condurango"},
{name: "Cockles - dietary"},
{name: "Symphytum"},
{name: "Symphytum, NOS"},
{name: "Comfrey"},
{name: "CORN SILK"},
{name: "corydalis"},
{name: "Corydalis canadensis"},
{name: "Corydalis Bungeana"},
{name: "Colocynthis vulgaris"},
{name: "Bitter-Apple"},
{name: "Colocynthis"},
{name: "costus"},
{name: "Wheat grass"},
{name: "poaceae"},
{name: "centaurea"},
{name: "Cornflower"},
{name: "viburnum"},
{name: "Viburnum opulus"},
{name: "Cocos nuciferas"},
{name: "gossypium"},
{name: "Gossypium Herbaceum"},
{name: "Polyethylene glycosylated creatine"},
{name: "creatines"},
{name: "Creatine Ethyl Ester"},
{name: "N-amidinosarcosine"},
{name: "Magnesium creatine chelate"},
{name: "Creatine pyruvate"},
{name: "N-Methyl-N-guanylglycine"},
{name: "Creatine nitrate"},
{name: "CALTHA PALUSTRIS"},
{name: "Croton eluteria"},
{name: "croton"},
{name: "Cumin (spice)"},
{name: "Free plant stanols"},
{name: "Plant Stanols"},
{name: "Plant stanol esters"},
{name: "Kefir, plant based"},
{name: "Plant Phytosterols"},
{name: "plants"},
{name: "Plant-Source Digestive Enzymes"},
{name: "Plant sterol esters"},
{name: "Cyclamen purpurascens"},
{name: "Cyclamen"},
{name: "Cyclamen europaeum"},
{name: "cypress"},
{name: "Spurges"},
{name: "Alpine Cranberry"},
{name: "cranberry extract"},
{name: "Cranberry"},
{name: "Papaver rhoeas"},
{name: "Corn poppy"},
{name: "TURNERA DIFFUSA WHOLE"},
{name: "Damiana"},
{name: "Turnera diffusa var. aphrodisiaca"},
{name: "Turnera diffusa"},
{name: "Turnera diffusa var aphrodisiaca"},
{name: "narcissus"},
{name: "Deer allergen"},
{name: "Deer Velvet"},
{name: "Datura lurida"},
{name: "datura"},
{name: "Wrightia"},
{name: "Dandelion"},
{name: "taraxacum officinale"},
{name: "Taraxacum borealisinense"},
{name: "Taraxacum"},
{name: "Taraxacum dens leonis"},
{name: "d mannose"},
{name: "6-Deoxy-D-mannose"},
{name: "D-Mannose"},
{name: "delphinium"},
{name: "Delphinium staphisagria"},
{name: "Dichanthelium clandestinum"},
{name: "N,N-Dimethyl-2-hydroxyethylamine"},
{name: "Deanol"},
{name: "beta-Dimethylaminoethyl alcohol"},
{name: "dimethylaminoethanol"},
{name: "cordyceps"},
{name: "Date Palm"},
{name: "Date Palms"},
{name: "Desert Parsley"},
{name: "Lomatium dissectum"},
{name: "Dendrobium Sw., 1799"},
{name: "Duboisia myoporoides"},
{name: "DUBOISIA MYOPOROIDES WHOLE"},
{name: "Devil's Club"},
{name: "Oplopanax horridus"},
{name: "Oplopanax horridus (Sm.) Miq."},
{name: "salvia miltiorrhiza"},
{name: "Danshen"},
{name: "Durio zibethinus"},
{name: "Durian"},
{name: "Scotch Broom"},
{name: "cytisus"},
{name: "Juniperus virginianas"},
{name: "Pinus palustris/other pinus species"},
{name: "Pine Bark Extract"},
{name: "Pine"},
{name: "Pinus <genus>"},
{name: "Sambucus canadensis"},
{name: "American Elder"},
{name: "elder extract"},
{name: "Sambucus"},
{name: "Sambucus Nigra (unspecified)"},
{name: "Elder Flower"},
{name: "acid eicosapentaenoic"},
{name: "EDTA"},
{name: "edetic acid"},
{name: "Ecdysterone"},
{name: "elderberry"},
{name: "Sambucus nigra subsp. canadensis"},
{name: "inula"},
{name: "Elecampane"},
{name: "Inula helenium"},
{name: "Echinacea preparation"},
{name: "Echinacea"},
{name: "emu Oil"},
{name: "Elm"},
{name: "Juglans regia allergenic extract"},
{name: "LEMNA MINOR"},
{name: "ERGOTHIONEINE"},
{name: "Equol"},
{name: "Berberis vulgaris"},
{name: "Berberis"},
{name: "Berberis Sargentiana"},
{name: "Berberis (plant)"},
{name: "Barberry"},
{name: "Eucalyptus odorata"},
{name: "Eucalyptus globulus"},
{name: "Eucalyptus globulus oil"},
{name: "Eucalyptus"},
{name: "Eucalyptus essential oil"},
{name: "Castanea vesca"},
{name: "Frangula alnus"},
{name: "frangula"},
{name: "Buckthorn"},
{name: "Frangula purshiana"},
{name: "Ma huang extract"},
{name: "Ephedra"},
{name: "Ephedra sinica"},
{name: "Ephedra vulgaris"},
{name: "Mistletoe (European)"},
{name: "Mistletoe"},
{name: "viscum album"},
{name: "European Mistletoe"},
{name: "Euphorbia"},
{name: "Euphorbia hirta"},
{name: "Euphorbia cyparissias"},
{name: "Euphorbia lathyrus"},
{name: "Sulphoxide, Dimethyl"},
{name: "Dimethylsulfoxide"},
{name: "Evening primrose oil"},
{name: "Evening primrose"},
{name: "Oleum oenothera biennis (oil)"},
{name: "oenothera biennis"},
{name: "Docosahexaenoic acid"},
{name: "Mandragora e radice siccata"},
{name: "Mandragora officinarum"},
{name: "Mandrake, European"},
{name: "Claviceps purpurea"},
{name: "ergot fungus"},
{name: "euphrasia"},
{name: "Eyebright"},
{name: "Draconis Resina"},
{name: "Dragon's Blood"},
{name: "Fenugreek"},
{name: "Euodia Fruit"},
{name: "Evodiae pteleaefolia"},
{name: "Evodia"},
{name: "Eurycoma Jack"},
{name: "Eurycoma Longifolia"},
{name: "Fermented Wheat Germ Extract"},
{name: "Cortex Phellodendri"},
{name: "Bark - plant part"},
{name: "Cortex magnoliae officinalis"},
{name: "Oak Bark"},
{name: "Cortex moutan"},
{name: "Neopanax arboreus"},
{name: "Abies nigra"},
{name: "abies"},
{name: "Abies canadensis"},
{name: "Abies pectinata"},
{name: "Bassia scoparia"},
{name: "scoparia, Bassia"},
{name: "FIG"},
{name: "Figs - dietary"},
{name: "Fish protein hydrolysate"},
{name: "Fish hydrolysate"},
{name: "Fish proteins and polysaccharides"},
{name: "Fish Oil"},
{name: "Fish peptide extract"},
{name: "fish - non-drug agent"},
{name: "Fish lecithin"},
{name: "Fish (including shell)"},
{name: "Oleum morrhuae"},
{name: "Oleum eucalypti"},
{name: "Oil of muscade"},
{name: "Oleum animale"},
{name: "Oleum jecoris aselli"},
{name: "Patchouly Oil"},
{name: "Krill Oil"},
{name: "Borago Officinalis Seed Oil"},
{name: "Oleum gaultheriae"},
{name: "Seal Oil"},
{name: "Oleum santali"},
{name: "Oleum carvi"},
{name: "Squid's Oil"},
{name: "Oleum Menthae Dementholatum"},
{name: "Origanum Vulgare Leaf Oil"},
{name: "Ylang ylang Oil"},
{name: "Oat Oil"},
{name: "Oleum terebinthinae"},
{name: "plant oils"},
{name: "Salmon Oil"},
{name: "Algal Oil"},
{name: "Clostridiopeptidase B"},
{name: "Ficin"},
{name: "Fluoride"},
{name: "Folic Acid"},
{name: "Lactobacillus casei factor"},
{name: "Fallopia multiflora plant"},
{name: "Reynoutria multiflora"},
{name: "Fo-Ti"},
{name: "Fallopia multiflora"},
{name: "Figwort"},
{name: "scrophularia nodosa"},
{name: "Forsythia"},
{name: "Fructus Forsythiae"},
{name: "Fennel"},
{name: "Sweet fennel essential oil"},
{name: "Genus: Digitalis"},
{name: "Digitalis Purpurea"},
{name: "Digitalis"},
{name: "Frankincense"},
{name: "Boswellia sacra"},
{name: "Fructo-oligosaccharides"},
{name: "Oligosaccharide (substance)"},
{name: "Fucus vesiculosus"},
{name: "Bladder wrack extract"},
{name: "Ascophyllum nodosum/Fucus vesiculosus blend"},
{name: "Galphimia, NOS"},
{name: "gamboge"},
{name: "Garcinia cambogia"},
{name: "Gambogia"},
{name: "galbanum"},
{name: "Fumaria <plant>"},
{name: "Fumitory"},
{name: "gamma-Aminobutyric acid"},
{name: "gamma aminobutyric acid"},
{name: "4 Butyrolactone"},
{name: "Hydroxybutyrate"},
{name: "Gamma oryzanol"},
{name: "Gamma Glutamylcysteines"},
{name: "Gamma-Butyrobetaine"},
{name: "Gamma-carotene"},
{name: "Gammar"},
{name: "Fadogia, NOS"},
{name: "Agrestia"},
{name: "Gardenia jasminoides"},
{name: "gardenia"},
{name: "Fructus Gardeniae"},
{name: "Garlic"},
{name: "allium sativum"},
{name: "Feverfew"},
{name: "Garden Cress"},
{name: "Lepidium sativums"},
{name: "Lepidium sativum"},
{name: "Gelsemium"},
{name: "Gelatin"},
{name: "Gelatina nigra"},
{name: "Gelatin food"},
{name: "Gelatin powder"},
{name: "Germanium, NOS"},
{name: "Germanium"},
{name: "Gentian"},
{name: "Gentiana lutea"},
{name: "Gentiana (plant)"},
{name: "Large-leaf gentian"},
{name: "Flaxseed Oil"},
{name: "linseed oil"},
{name: "Ginger"},
{name: "extract ginger"},
{name: "teucrium"},
{name: "Privet"},
{name: "Glossy Privet"},
{name: "Matricaria recutita"},
{name: "Matricaria chamomilla extract"},
{name: "German Chamomile"},
{name: "Polysaccharide"},
{name: "Genistein"},
{name: "genestein"},
{name: "4',5,7-Trihydroxyisoflavone"},
{name: "Golden ragwort"},
{name: "caseinomacropeptide"},
{name: "Glucosamine Sulfate"},
{name: "sulfate glucosamine"},
{name: "Goat Rues"},
{name: "Coffee, NOS"},
{name: "Green Coffee"},
{name: "Coffee cruda"},
{name: "gamma-Oryzanol"},
{name: "Oryzanol (substance)"},
{name: "Green tea Polyphenols-Phosphatidylcholine complex"},
{name: "Green tea (dietary)"},
{name: "Green tea"},
{name: "Green tea extract-Phosphatidylcholine complex"},
{name: "Green tea-Phosphatidylcholine complex"},
{name: "Green tea extract"},
{name: "Senecio vulgaris L."},
{name: "guaiacum"},
{name: "Partially hydrolyzed guar gum"},
{name: "Guar flour"},
{name: "Guar Gum"},
{name: "Partially hydrolysed guar gum"},
{name: "Guava"},
{name: "Guava Fruit"},
{name: "Hawthorn"},
{name: "Hawthorn plant"},
{name: "Hawthorn Berry Extract"},
{name: "Hazelnut"},
{name: "Heather"},
{name: "Heather (plant)"},
{name: "Hemlock"},
{name: "spruce"},
{name: "Eupatorium cannabinum"},
{name: "Water Agrinomy"},
{name: "Hemp Agrimony"},
{name: "LAWSONE"},
{name: "Reed Herb"},
{name: "Holy Basil Herb"},
{name: "herb"},
{name: "Hericium erinaceus"},
{name: "Hibiscus"},
{name: "Hibiscus sabdariffa"},
{name: "Herb Paris"},
{name: "Paris quadrifolia"},
{name: "Ilex, NOS"},
{name: "Holly"},
{name: "L-Histidine"},
{name: "Histidine"},
{name: "l histidine"},
{name: "Hesperidin Complex"},
{name: "Hesperidin (substance)"},
{name: "Hesperidin"},
{name: "higenamine"},
{name: "Tramiprosate"},
{name: "Ocimum sanctum L."},
{name: "OCIMUM TENUIFLORUM WHOLE"},
{name: "Ocimum sanctum"},
{name: "Ocimum tenuiflorum"},
{name: "HONEY"},
{name: "Leptospermum scoparium Honey"},
{name: "Ivy (plant)"},
{name: "Ground Ivy"},
{name: "Honeysuckle antigen"},
{name: "Honeysuckle"},
{name: "Honeysuckle flower"},
{name: "Horse Chestnut"},
{name: "aesculus hippocastanum"},
{name: "equisetum"},
{name: "Horsetail"},
{name: "Equisetum hyemale"},
{name: "Gumweed"},
{name: "N,N-dimethyltyramine"},
{name: "hordenine"},
{name: "Armoracia rusticana"},
{name: "horseradish"},
{name: "Hyacinthus, NOS"},
{name: "BEAN"},
{name: "Bean pod"},
{name: "Ignatius Bean"},
{name: "Hydrastis canadensis L."},
{name: "Goldenseal"},
{name: "Goldenseals"},
{name: "Hydrastis canadensis"},
{name: "Egg shell membrane"},
{name: "Egg Albumen"},
{name: "Egg"},
{name: "Hyssop Oil"},
{name: "Hyssop"},
{name: "idébénone"},
{name: "Idebenone"},
{name: "Iceland Moss"},
{name: "Cetraria islandica"},
{name: "Black Henbane"},
{name: "Henbane"},
{name: "Hydrangea"},
{name: "Tree hydrangea"},
{name: "Indian Long Pepper"},
{name: "Piper longum"},
{name: "Long Pepper"},
{name: "Greater Celandine"},
{name: "Indian snakeroot"},
{name: "rauwolfia"},
{name: "Rauwolfia serpentina"},
{name: "Indian colchicum"},
{name: "Indian Sarsparilla"},
{name: "Indian Rhubarb (herb powder)"},
{name: "India - zebrafish"},
{name: "Indian Gooseberry"},
{name: "Tabernanthe iboga Baill."},
{name: "myo-Inositol hexakis(dihydrogen phosphate)"},
{name: "Inositol"},
{name: "cis-1,2,3,5-trans-4,6-Cyclohexanehexol"},
{name: "myo-inositol, hexa-3-pyridinecarboxylate"},
{name: "chiro-inositol"},
{name: "D-Chiro-inositol"},
{name: "Inositol Nicotinate"},
{name: "Cyclohexanehexol"},
{name: "myo-Inositol-hexakisphosphate 4-phosphohydrolase"},
{name: "myo-Inositol-hexakisphosphate 3-phosphohydrolase"},
{name: "Inositol hexaniacinate"},
{name: "Myo-inositol"},
{name: "Hexanicotinyl cis-1,2,3,5-trans-4,6-cyclohexane"},
{name: "Arginine silicate inositol"},
{name: "1,2,3,5/4,6-cyclohexanehexol"},
{name: "3-O-Methyl-D-chiro-inositol"},
{name: "Inosine Phosphate"},
{name: "Hypoxanthosine"},
{name: "inosine"},
{name: "Nicotinate"},
{name: "Iodine"},
{name: "Povidone-Iodine"},
{name: "3-Hydroxymethylindole"},
{name: "Indole-3-Carbinol"},
{name: "Indole-3-Carbinol (I3C)"},
{name: "Indole-3-methanol"},
{name: "Ipeca"},
{name: "syrup of ipecac"},
{name: "Ipecacuanha"},
{name: "Isatis"},
{name: "Isatis Leaf"},
{name: "Woad"},
{name: "Isatis Tinctoria"},
{name: "coccinia"},
{name: "Jackfruit - dietary"},
{name: "Ignatius"},
{name: "Jalap Preparation"},
{name: "Jalapa"},
{name: "Indium"},
{name: "Indium, NOS"},
{name: "Indium metallicum"},
{name: "Eugenia jambolana"},
{name: "Syzygium cumini"},
{name: "Eugenia jambolana Lam."},
{name: "Jambolan"},
{name: "Syzygium jambolanum"},
{name: "Pilocarpus jaborandi preparation"},
{name: "Jaborandi"},
{name: "Persimmon"},
{name: "7-(1-methylethoxy)-3-phenyl-4H-1-benzopyran-4-one"},
{name: "Ipriflavone"},
{name: "Jasminum officinale"},
{name: "Jasmine absolute"},
{name: "jessamine"},
{name: "Java Tea"},
{name: "Japanese Mint"},
{name: "Mint"},
{name: "Jewelweed"},
{name: "impatiens balsamina"},
{name: "LINARIA VULGARIS"},
{name: "Stramonium"},
{name: "Stramonium foetidum"},
{name: "Datura stramonium (plant)"},
{name: "Datura stramonium"},
{name: "Jiao Gu-lan"},
{name: "Jiaogulan"},
{name: "Smoked Plum"},
{name: "Japanese Apricot"},
{name: "Karaya Gum"},
{name: "Sterculia acuminata"},
{name: "Sterculia"},
{name: "Kava"},
{name: "Kava kava"},
{name: "Kefir"},
{name: "Lactobacillus kefiri"},
{name: "Kefir grains"},
{name: "Kefir grains, microbe based"},
{name: "catha edulis"},
{name: "Kaolin"},
{name: "China Clay"},
{name: "Knotweed"},
{name: "POLYGONUM ARENASTRUM WHOLE"},
{name: "kinetin"},
{name: "Pueraria montana var. lobata"},
{name: "Kudzu"},
{name: "Pueraria mirifica"},
{name: "Pueraria omeiensis"},
{name: "Dolichos lobatus"},
{name: "Pueraria Montana Var. thomsonii"},
{name: "Krebiozen"},
{name: "Propionyl-L-Carnitine"},
{name: "Levocarnitine"},
{name: "L-Carnitine"},
{name: "Acetyl L-Carnitine"},
{name: "Krill/fish oil blend"},
{name: "Krill"},
{name: "5-Hydroxy-L-tryptophan"},
{name: "L-Tryptophan"},
{name: "l tryptophan"},
{name: "Ledum groenlandicums"},
{name: "Lactobacillus acidophilus Rosell-52"},
{name: "Lactobacillus, NOS"},
{name: "Lactobacillus acidophilus spent culture supernatant"},
{name: "Lactobacillus acidophilus CUL-21"},
{name: "Lactobacillus brevis"},
{name: "Lactobacillus casei"},
{name: "Lactobacillus acidophilus"},
{name: "Lactobacillus bulgaricus"},
{name: "Lactobacillus"},
{name: "Lactobacillus acidophilus CUL-60"},
{name: "Laminariales"},
{name: "galium"},
{name: "Lactotransferrin"},
{name: "Lactoferrin"},
{name: "laburnum"},
{name: "Dodecanoic acid"},
{name: "Lauric acid"},
{name: "Juniper"},
{name: "Turpentine"},
{name: "Turpentine Oil"},
{name: "Turpentine, Oil"},
{name: "Turpentine essential oil"},
{name: "Oil of turpentine"},
{name: "Job's Tears"},
{name: "coix"},
{name: "Lathyrus, NOS"},
{name: "Lathyrus"},
{name: "lecithins"},
{name: "Lecithin"},
{name: "lemongrass"},
{name: "cymbopogon nardus"},
{name: "lavandula"},
{name: "Lavender"},
{name: "Lavender essential oil"},
{name: "chelidonium"},
{name: "Lentinan"},
{name: "Licorice"},
{name: "glycyrrhiza"},
{name: "Wild Berry-Apple Concentrate"},
{name: "berry preparation"},
{name: "Lilium lancifolium"},
{name: "Lily of the Valley"},
{name: "Lily"},
{name: "White Lily"},
{name: "Larch arabinogalactan"},
{name: "larix"},
{name: "Arabinogalactan"},
{name: "Larix occidentalis Arabinogalactan"},
{name: "Galactoarabinan"},
{name: "Lemon"},
{name: "Lemon Verbane"},
{name: "Lemon Extract"},
{name: "lemon Verbena"},
{name: "Lemon Bioflavonoids"},
{name: "Citrus limonum"},
{name: "Citrus limon plant"},
{name: "officinalis melissa"},
{name: "Melissa officinalis"},
{name: "calcium oxide"},
{name: "Lime tree"},
{name: "Lime"},
{name: "Lychee fruit"},
{name: "Mace brand of omega-Chloroacetophenone"},
{name: "Nutmeg & Mace"},
{name: "catharanthus roseus"},
{name: "Vinca rosea"},
{name: "magnolia"},
{name: "Magnolia officinalis"},
{name: "Magnolia officinalis var. biloba"},
{name: "Magnolia glauca"},
{name: "macadamia nut"},
{name: "Maidenhair Fern"},
{name: "ferns"},
{name: "Dryopteris filix-mas"},
{name: "Dryopteris filix mas"},
{name: "Pulmonaria L., 1753"},
{name: "Sticta pulmonaria"},
{name: "MANGANESE"},
{name: "Manganese (HVP) chelate"},
{name: "Manganese acetate"},
{name: "Thorn substance"},
{name: "mannans"},
{name: "1,4-beta-D-mannan mannanohydrolase"},
{name: "Pinus pinaster bark extract"},
{name: "cluster pine"},
{name: "Pinus pinaster"},
{name: "Marijuana"},
{name: "marihuana"},
{name: "ALETRIS FARINOSA WHOLE"},
{name: "Marjoram (Spice)"},
{name: "Marjoram"},
{name: "BRUNFELSIA UNIFLORA WHOLE"},
{name: "Masterwort"},
{name: "Marshmallow"},
{name: "Tea (not specified)"},
{name: "Tea, NOS"},
{name: "Red Bush Tea"},
{name: "Mormon Tea"},
{name: "Rooibos Tea"},
{name: "Marsh Tea"},
{name: "Oolong Tea"},
{name: "melanotan-II"},
{name: "N-[2-(5-Methoxy-1H-indol-3-yl)ethyl]acetamide"},
{name: "N-Acetyl-5-methoxytryptamine"},
{name: "Melatonin"},
{name: "Mercury"},
{name: "Mesoglycan"},
{name: "Mentzelia"},
{name: "Methoxylated flavones"},
{name: "Polymethoxylated flavones"},
{name: "Flavones [Chemical/Ingredient]"},
{name: "Daphne mezereum (plant)"},
{name: "Richadella dulcifica"},
{name: "filipendula"},
{name: "Filipendula ulmaria"},
{name: "Meadowsweet"},
{name: "Dry Milk"},
{name: "Milk Thistle"},
{name: "Milk protein hydrolysate"},
{name: "Milk"},
{name: "milk cow's"},
{name: "Milk basic protein"},
{name: "dodecanoic acid, monoester with 1,2,3-propanetriol"},
{name: "Moringa"},
{name: "S - adenosyl - L - Methionine tosylate"},
{name: "S-Adenosyl-L-methionine"},
{name: "L-Methionine"},
{name: "DL-Methionine"},
{name: "S-(5'-Desoxyadenosin-5'-yl)-l-methionine"},
{name: "Methionine"},
{name: "Methionine product"},
{name: "N-acetyl-L-methionine"},
{name: "Seleno Methionine"},
{name: "Magnesium Aluminum Silicate"},
{name: "Magnesium diglycinate"},
{name: "Magnesium glycyl glutamine"},
{name: "Magnesium Bisglycinate"},
{name: "Magnesium carbonate, Heavy"},
{name: "Magnesium carbonicum"},
{name: "Magnesium hydroxide"},
{name: "Magnesium glucoheptonate"},
{name: "Magnesium"},
{name: "Magnesium(II) hydroxide"},
{name: "Magnesium metallicum"},
{name: "Magnesium chloratum"},
{name: "Magnesium phosphoricum"},
{name: "Magnesium octanoate"},
{name: "leonurus"},
{name: "Motherwort"},
{name: "Mountain Ash"},
{name: "Sorbus, NOS"},
{name: "Mouse antigen"},
{name: "creeping-Jenny"},
{name: "Lysimachia nummularia"},
{name: "polysaccharide MGN3"},
{name: "MGN-3"},
{name: "LINUM CATHARTICUM"},
{name: "Myrrh"},
{name: "Myrrha"},
{name: "Bola resin"},
{name: "Artemisia Annua"},
{name: "Artemisia Herba-Alba"},
{name: "Wormwood"},
{name: "Artemisia (plant)"},
{name: "Mugwort"},
{name: "Artemisia"},
{name: "Cina artemisia"},
{name: "myrtus"},
{name: "Myrcia"},
{name: "verbascum"},
{name: "Verbascum densiflorum"},
{name: "Mullein"},
{name: "nadh"},
{name: "Glucosamine"},
{name: "Glucosamine HCL"},
{name: "N-Acetyl-L-Glucosamine"},
{name: "Glucosamine Sulfate*KCl"},
{name: "N-Acetyl-beta-D-glucosamine"},
{name: "N-Acetyl Glucosamine"},
{name: "Glucosamine Sulfate*Potassium Chloride"},
{name: "glucosamines"},
{name: "Glucosamine (unspecified)"},
{name: "N-acetyl-D-glucosamine"},
{name: "nattokinase [Chemical/Ingredient]"},
{name: "Nattokinase"},
{name: "Molybdenum"},
{name: "Molybdenum metallicum"},
{name: "3-methylpentane"},
{name: "3-Pyridinecarboxamide"},
{name: "Niacinamide"},
{name: "b3 vitamin"},
{name: "Nicotinamidum"},
{name: "Green Shell Mussel"},
{name: "Mussels - dietary"},
{name: "New Zealand Green Lipped Mussel"},
{name: "L-Acetyl n-Cysteine"},
{name: "L-Cysteine"},
{name: "N-Acetyl-L-cysteine"},
{name: "cysteines"},
{name: "N-Acetyl Cysteine"},
{name: "D-Ribose-L-cysteine"},
{name: "Cysteine"},
{name: "Noni"},
{name: "morinda citrifolia"},
{name: "New Jersey Tea"},
{name: "Red Root"},
{name: "Ceanothus americanus"},
{name: "Nux vomica"},
{name: "Maple antigen"},
{name: "Oats"},
{name: "Oats (Dietary)"},
{name: "Octacosanol"},
{name: "1-Octacosanol"},
{name: "myristica fragrans"},
{name: "Octodrine"},
{name: "Nerium oleander"},
{name: "Oleander"},
{name: "Olive"},
{name: "Olive antigen"},
{name: "Olive Leaf"},
{name: "Musci"},
{name: "quercus"},
{name: "Quercus glandium spiritus"},
{name: "Onion"},
{name: "Antidote"},
{name: "Papaver somniferum exudate"},
{name: "Balsam"},
{name: "Balsas J.Jimenez Ram. & K.Vega, 2011"},
{name: "Orienta"},
{name: "Oriental arborvitae"},
{name: "Northera"},
{name: "oscillococcinum"},
{name: "Nasturtiums"},
{name: "Nasturtium officinale"},
{name: "Nasturtium aquaticum"},
{name: "Oregano"},
{name: "Iris florentina (plant)"},
{name: "Iris florentina"},
{name: "Orris"},
{name: "2,5 Diaminopentanoic Acid"},
{name: "Ornithine"},
{name: "N5-(Aminocarbonyl)-L-ornithine"},
{name: "Ginseng (Asian)"},
{name: "Ginseng"},
{name: "Panax saponins"},
{name: "panax"},
{name: "Panax ginseng"},
{name: "Ginseng (American)"},
{name: "Panax ginseng-Phosphatidylcholine complex"},
{name: "Panax Pseudoginseng"},
{name: "Ginseng, Panax"},
{name: "Ren Shen"},
{name: "Panax Notoginseng"},
{name: "Panax ginseng C.A. Meyer (Araliaceae)"},
{name: "Ginseng quinquefolia"},
{name: "Ginseng saponins"},
{name: "Pantothenic acid"},
{name: "D-Pantothenic Acid"},
{name: "Pantothenic Acid (Vitamin B5)"},
{name: "acid pantothenic"},
{name: "Nickel"},
{name: "Palm Oil"},
{name: "Chaste tree"},
{name: "Trees (plant)"},
{name: "Tree Turmeric"},
{name: "Pagoda Tree"},
{name: "PARSLEY"},
{name: "Passiflora Edulis"},
{name: "Passionflower"},
{name: "passiflora"},
{name: "Parsnip"},
{name: "Parsnips - dietary"},
{name: "Pareira"},
{name: "Chondrodendron tomentosum"},
{name: "Pantethine"},
{name: "D-Pantethine"},
{name: "peruvian balsam"},
{name: "Pheasant antigen"},
{name: "2-Phenylethylamine"},
{name: "Phenylethylamine (PEA)"},
{name: "Phenylethylamine PEA)"},
{name: "phenethylamines"},
{name: "N-Benzyl-Alpha-Phenylethylamine"},
{name: "Peyote agent"},
{name: "phaseolus"},
{name: "Phaseolus vulgaris var. vulgaris"},
{name: "Phaseolus radiatus"},
{name: "Phaseolus vulgaris"},
{name: "4-amino-3-phenylbutyric acid"},
{name: "Phleum pratense"},
{name: "phleum"},
{name: "PHLORIZIN"},
{name: "Phloridzinum"},
{name: "Phenylalanine"},
{name: "D-phenylalanine"},
{name: "L-Phenylalanine"},
{name: "3,5-Diiodo-4-hydroxy-beta-phenylalanine"},
{name: "dl-Phenylalanine"},
{name: "Pimpinella"},
{name: "Pimpinella anisum"},
{name: "Pimpinella L."},
{name: "Phosphate"},
{name: "Phosphate Salts"},
{name: "Phosphate Ion"},
{name: "Sodium Phosphate, Monobasic"},
{name: "Ferrum Phosphate"},
{name: "Sodium Phosphate, Dibasic"},
{name: "Sodium Phosphate, Monobasic (anhydrous)"},
{name: "Neem"},
{name: "Azadirachta indica"},
{name: "Nimba"},
{name: "Plant Sterols"},
{name: "Phytosterols"},
{name: "Phytosterols esters"},
{name: "Free Plant Sterols"},
{name: "Sterols"},
{name: "Phytosterol complex"},
{name: "Pleurisy"},
{name: "Poison Ivy"},
{name: "Phytolacca decandra"},
{name: "Inkberry"},
{name: "Pokeweed"},
{name: "Phytolacca americana"},
{name: "Policosanol (product)"},
{name: "Policosanol"},
{name: "Podophyllum peltatum"},
{name: "podophyllum"},
{name: "Polydextrose"},
{name: "polydestrose"},
{name: "Pomegranate"},
{name: "Poppy seed (dietary)"},
{name: "Poriae Rubrae"},
{name: "Poria"},
{name: "Sclerotium Poriae Cocos"},
{name: "Poria <fungus>"},
{name: "Solanum tuberosums"},
{name: "Potato"},
{name: "Potato protein"},
{name: "PLE"},
{name: "3beta-Hydroxypregn-5-en-20-one"},
{name: "Pregnenolone"},
{name: "Prickly Pear Cactus"},
{name: "Cactus"},
{name: "Finger Cactus"},
{name: "Cactus grandiflorus"},
{name: "Family Cactaceae"},
{name: "Pear"},
{name: "Prickly Pear Leaf"},
{name: "Argentina"},
{name: "Potentilla anserina"},
{name: "Poplar"},
{name: "Populus, NOS"},
{name: "Populus tremuloides"},
{name: "Propion"},
{name: "Procaine (product)"},
{name: "Progesterone"},
{name: "Propolis (fungal genus)"},
{name: "Bee Propolis"},
{name: "Propolis"},
{name: "Lythrum salicaria"},
{name: "Loosestrife, Purple"},
{name: "Pellitory"},
{name: "2-Oxopropanoate"},
{name: "Pyruvate"},
{name: "QUASSIA AMARA WHOLE"},
{name: "Quassia"},
{name: "Quassia amara"},
{name: "Pyrethrum (plant)"},
{name: "Pulsatilla nigricans"},
{name: "Pulsatilla"},
{name: "Pulsatilla nuttalliana"},
{name: "Pulsatilla vulgaris"},
{name: "Quinoa"},
{name: "3,3',4',5,7-Pentahydroxyflavone"},
{name: "Quercetin"},
{name: "2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxy-4H-1-benzopyran-4-one"},
{name: "Quercetin dihydrate"},
{name: "Quercetin chalcone"},
{name: "Poinsettia"},
{name: "Rabdosia Hassk., 1842"},
{name: "Quince - dietary"},
{name: "Quince"},
{name: "Queen's Delight Root"},
{name: "Queen's Delight"},
{name: "Bush"},
{name: "Maroon Bush"},
{name: "Fountain bush"},
{name: "Radish"},
{name: "Raphanus, NOS"},
{name: "Red maple"},
{name: "pinellia"},
{name: "Massa pinelliae fermentata"},
{name: "Pinelliae Fermentata"},
{name: "Pinellia Ternata"},
{name: "saponaria officinalis"},
{name: "Yeast hydrolysate"},
{name: "Yeast extract"},
{name: "Red Yeast Rice"},
{name: "Selenium Yeast"},
{name: "Yeast"},
{name: "Red Yeast"},
{name: "Dried Yeast"},
{name: "Rehmannia glutinosa preparated"},
{name: "Rehmannia glutinosa"},
{name: "Rehmannia"},
{name: "Genus Rehmannia"},
{name: "Prepared Rehmanniae glutinosa"},
{name: "D-Ribose"},
{name: "d ribose"},
{name: "Ribose"},
{name: "Cistus canadensis"},
{name: "Rock Rose"},
{name: "Halimium canadense (L.) Grosser"},
{name: "Rhubarb"},
{name: "Rheum rhabarbarum"},
{name: "Ribonucleic Acid"},
{name: "RNA and DNA"},
{name: "RNA"},
{name: "RNA & DNA"},
{name: "Geranium Thumbergii"},
{name: "Pelargonium graveolens"},
{name: "Geranium robertianum"},
{name: "Geranium"},
{name: "Rosa Roxburghii"},
{name: "rosa"},
{name: "Rose hip"},
{name: "Rose"},
{name: "Rose hips"},
{name: "ruta"},
{name: "Rue"},
{name: "Herniaria L., 1753"},
{name: "Chamaemelum nobiles"},
{name: "Anthemis nobilis"},
{name: "Lolium (plant)"},
{name: "Sedges, Flat"},
{name: "Saffron"},
{name: "Crocus Sativus flower extract"},
{name: "Salacia <angiosperm>"},
{name: "Salacia"},
{name: "salatrim"},
{name: "S-adenosylmethionine"},
{name: "SAM-e"},
{name: "SAMe"},
{name: "S adenosylmethionine"},
{name: "Salvia divinorum"},
{name: "Safflower"},
{name: "Sarsaparilla"},
{name: "Smilax sarsaparilla"},
{name: "Genus Sanicula"},
{name: "Sanicula aqua"},
{name: "Sanicula"},
{name: "sassafras"},
{name: "Anagallis, NOS"},
{name: "Lindernia anagallis"},
{name: "Anagallis phoenicea Scop."},
{name: "Scarlet red"},
{name: "boulardii, Saccharomyces"},
{name: "Saccharomyces boulardii lyo"},
{name: "Saccharomyces boulardii"},
{name: "Quercetin-3-rutinoside"},
{name: "rutosides"},
{name: "Quercetin-3-rutinoside trihydrate"},
{name: "Rutin"},
{name: "Schizonepeta (Benth.) Briq., 1896"},
{name: "Schizonepeta"},
{name: "Fructus Schisandrae chinensis"},
{name: "Schisandra"},
{name: "Schizandra"},
{name: "Scopolia (substance)"},
{name: "ONOPORDUM ACANTHIUM WHOLE"},
{name: "Sea Buckthorn"},
{name: "Hippophae rhamnoides"},
{name: "hippophae"},
{name: "Securinega Comm. ex Juss., 1789"},
{name: "Secretin preparation"},
{name: "Mesembryanthemum sect. Planifolia"},
{name: "Sceletium"},
{name: "Sesame - dietary"},
{name: "Rhododendron"},
{name: "Shark cartilage"},
{name: "Shark Liver Oil"},
{name: "Serratiopeptidase"},
{name: "Serrapeptase"},
{name: "Serrapeptase (substance)"},
{name: "Serratiopeptidase/Serrapeptase"},
{name: "Senna"},
{name: "Senna alexandrina"},
{name: "Senna angustifolia"},
{name: "Cassia acutifolia"},
{name: "Senna alexandrinas"},
{name: "Folium sennae"},
{name: "Cassia senna"},
{name: "Ratanies"},
{name: "Krameria triandra"},
{name: "Smooth Alder"},
{name: "Alder antigen"},
{name: "Sodium phosphate"},
{name: "Sodium oleate"},
{name: "Sodium pyruvate"},
{name: "Sodium hexametaphosphate"},
{name: "Sodium Chloride"},
{name: "Sodium fluoride"},
{name: "Sodium monofluorophosphate"},
{name: "Sodium copper chlorophyllin"},
{name: "Sodium"},
{name: "Sodium-D-aspartate"},
{name: "Sodium muriaticum"},
{name: "dietary sodium"},
{name: "Sodium dihydrogen phosphate hydrate"},
{name: "Sodium bicarbonate"},
{name: "Sour Cherry"},
{name: "Cherry"},
{name: "Prunus cerasus"},
{name: "Wild Cherry"},
{name: "Cerasus vulgaris"},
{name: "Polygonatum Sibiricum"},
{name: "Polygonatum"},
{name: "Solomon's Seal"},
{name: "bicarbonates sodium"},
{name: "Sodium hydrogen carbonate"},
{name: "Oils, Soybean"},
{name: "Soya oil"},
{name: "Soybean oil"},
{name: "Origanum (plant)"},
{name: "Spartium scoparium"},
{name: "Spartium L., 1753"},
{name: "rumex"},
{name: "Sorrel"},
{name: "Dock"},
{name: "Sheep Sorrel"},
{name: "Sheep Sorrel (herb powder)"},
{name: "Rumex acetosella"},
{name: "Polygonum cuspidatum"},
{name: "Polygonum punctatum"},
{name: "polygonum"},
{name: "Polygonum multiflorum"},
{name: "Spiny Restharrow"},
{name: "Ononis plant"},
{name: "Alum"},
{name: "Spotted Geranium"},
{name: "Geranium maculatum"},
{name: "Mitchella repens"},
{name: "Squill (substance)"},
{name: "Squalamine"},
{name: "Illicium verum"},
{name: "Star Anise"},
{name: "Star of Bethlehem"},
{name: "Ornithogalum, NOS"},
{name: "St. John's wort extract"},
{name: "St. John's Wort"},
{name: "Soy isoflavones"},
{name: "Soy"},
{name: "Soy fiber"},
{name: "Soy phosphatidyl"},
{name: "Soy fibre"},
{name: "Stereospermum suaveolens"},
{name: "Stereospermum Cham., 1833"},
{name: "Storax"},
{name: "Stinging Nettle"},
{name: "urtica dioica"},
{name: "Nettle"},
{name: "White Dead Nettle Flower"},
{name: "Strontium carbonicum"},
{name: "Strontium nitricum"},
{name: "Strontium, NOS"},
{name: "Strontium bromatum"},
{name: "Strontium"},
{name: "Strontium chloride hexahydrate"},
{name: "Strontium carbonate"},
{name: "Strontium Acetate Hemihydrate"},
{name: "Strontium dilactate"},
{name: "Fragaria ananassa"},
{name: "Strawberry leaves liquid extract"},
{name: "Fragaria x ananassa"},
{name: "Strawberry"},
{name: "Fragaria x ananassa cv. Orleans"},
{name: "Strophanthus"},
{name: "Strophanthus gratus"},
{name: "Strophanthus hispidus"},
{name: "Strophanthus, NOS"},
{name: "Sulbutiamine"},
{name: "2-isobutyrylthiamine disulfide"},
{name: "Spearmint"},
{name: "Mentha spicata"},
{name: "Mentha spicatas"},
{name: "Sunflower Oil"},
{name: "oil sunflower"},
{name: "Gliadin-Superoxide dismutase complex"},
{name: "Superoxide dismutase"},
{name: "superoxide anion"},
{name: "Sundew"},
{name: "Prunus amygdalus"},
{name: "Sweet Almond"},
{name: "ASCLEPIAS INCARNATA WHOLE"},
{name: "Sweet Annie"},
{name: "Sweet Violet"},
{name: "Sweets"},
{name: "Sweet Woodruff"},
{name: "Sweet Orange"},
{name: "Sweet almond oil"},
{name: "melilotus"},
{name: "Sweet Clover"},
{name: "Rhus succedanea"},
{name: "Rhus toxicodendron"},
{name: "rhus"},
{name: "Sulfur"},
{name: "Sulfur iodatum"},
{name: "Sulfur (Colloidal)"},
{name: "Sulforafan"},
{name: "Tangerine"},
{name: "Tamarix L., 1753"},
{name: "Tamarind Spice"},
{name: "Tagetes"},
{name: "Genus Tagetes"},
{name: "Ragworts"},
{name: "Tansy Ragwort"},
{name: "Senecio jacobaea"},
{name: "Tanacetum, NOS"},
{name: "Tanacetum parthenium"},
{name: "Tansy"},
{name: "Taurine"},
{name: "L-taurine"},
{name: "taufon"},
{name: "Tea Tree Oil"},
{name: "oil tea tree"},
{name: "theacrine"},
{name: "Terminalia latipes"},
{name: "terminalia"},
{name: "Terminalia chebula"},
{name: "Terminalia ferdinandiana"},
{name: "theaflavins"},
{name: "L-Theanine"},
{name: "Theanine"},
{name: "L-glutamic acid-gamma-ethylamide"},
{name: "Thiamine"},
{name: "Vitamin B1"},
{name: "Thiaminum hydrochloricum"},
{name: "Thiamine (Vitamin B1)"},
{name: "Thiamin disulfide"},
{name: "thiamin"},
{name: "THREONINE"},
{name: "L-Threonine"},
{name: "Acids, Tannic"},
{name: "Tannin"},
{name: "Tannic Acid"},
{name: "vine"},
{name: "Squaw Vine"},
{name: "Thuja occidentalis"},
{name: "thuja"},
{name: "Thuja lobbi"},
{name: "extracts thyroid"},
{name: "TIRATRICOL"},
{name: "Thymus Satureioides"},
{name: "Thymus"},
{name: "Thymus suis"},
{name: "Thymus <angiosperm>"},
{name: "Polypeptide Thymus"},
{name: "Thyme"},
{name: "D-alpha-Tocopheryl Succinate"},
{name: "Succinate"},
{name: "Tarragon"},
{name: "Tarragon Herb"},
{name: "Dipteryx odoratas"},
{name: "factor transfer"},
{name: "Transfer Factor"},
{name: "Viola <angiosperm>"},
{name: "Clematis vitalba-flos"},
{name: "Old Man's Beard"},
{name: "Orange Bioflavonoids"},
{name: "Orange Flavor"},
{name: "Orange (unspecified)"},
{name: "Ailanthus altissimas"},
{name: "Ailanthus glandulosa"},
{name: "Ailanthus glandulosus"},
{name: "Nicotiana Tabacum"},
{name: "Nicotiana, NOS"},
{name: "Arbutus"},
{name: "Arbutus uva-ursi"},
{name: "Trichopus"},
{name: "Turmeric Curcuminoids-Phosphatidylcholine complex"},
{name: "Javanese Turmeric"},
{name: "Turmeric"},
{name: "alpha- and beta-Trypsin"},
{name: "Trypsin"},
{name: "Turkey antigen"},
{name: "Aleurites (plant)"},
{name: "Tragacanth, Gum"},
{name: "Tragacanth"},
{name: "Usnea"},
{name: "Usnea Barbata"},
{name: "Vanilla extract"},
{name: "Vanilla"},
{name: "Tin difluoride"},
{name: "Tin, NOS"},
{name: "Stannum iodatum"},
{name: "Stannum metallicum"},
{name: "Tin"},
{name: "Tin (II)-fluoride"},
{name: "Veronicae herba"},
{name: "Veronica officinalis"},
{name: "veronica"},
{name: "Tinospora Cordifolia"},
{name: "tinospora"},
{name: "Chrysopogon Trin., 1820"},
{name: "Vetiveria Zizanioides"},
{name: "Valerian"},
{name: "valeriana officinalis"},
{name: "Valerianna"},
{name: "Coriander (Spice)"},
{name: "Vitamin A"},
{name: "Retinol, all trans-"},
{name: "TOCOTRIENOLS"},
{name: "Tocotrienol concentrate"},
{name: "Mixed Tocotrienols"},
{name: "Mixed Tocotrienols/Tocopherols"},
{name: "Verbena"},
{name: "Verbena (Plant)"},
{name: "L-Tyrosine"},
{name: "para Tyrosine"},
{name: "N-Acetyl-L-tyrosine"},
{name: "Tyrosine"},
{name: "Vitamin B2"},
{name: "Vitamin B6"},
{name: "Vitamin E"},
{name: "VITAMINS"},
{name: "Vitamin C"},
{name: "Vitamin B5"},
{name: "Vitamin O"},
{name: "Vitamin A palmitate"},
{name: "Vitamin C (ascorbic acid)"},
{name: "Vitamin A aldehyde"},
{name: "Vitamin D"},
{name: "tylophora"},
{name: "Vitex agnus-castus"},
{name: "Chasteberry"},
{name: "Erysimum, NOS"},
{name: "Wasabia japonica"},
{name: "Wasabia"},
{name: "Vinpocetine"},
{name: "Vinpocetine (substance)"},
{name: "Oenanthe, NOS"},
{name: "Watercress"},
{name: "Rorippa nasturtium-aquaticum"},
{name: "Wheat Bran"},
{name: "Vitamin K"},
{name: "Vitamin B12"},
{name: "Lavendula angustifolia (Lavender) flower/leaf/stem"},
{name: "Lavendula angustifolia (Lavender) flower extract"},
{name: "Tagates erecta, flower"},
{name: "flowers"},
{name: "Flower Pollen"},
{name: "Flower polen extract"},
{name: "Aethusa cicuta Meck."},
{name: "cicuta"},
{name: "Wild Yam"},
{name: "Dioscorea villosa"},
{name: "Willardia"},
{name: "Willow Bark"},
{name: "Wintergreen preparation"},
{name: "Wintergreen"},
{name: "anemone"},
{name: "Anemone altaica"},
{name: "Witch Hazel"},
{name: "Hamamelis virginiana"},
{name: "Hamamelis virginica"},
{name: "Hamamelis virginiana e foliis"},
{name: "Savories"},
{name: "Dysphania ambrosioides"},
{name: "Wormseed"},
{name: "Chenopodium ambrosioide"},
{name: "Xanthan Gum"},
{name: "gums xanthan"},
{name: "ACHILLEA MILLEFOLIUM"},
{name: "Yarrow"},
{name: "Wood Sage"},
{name: "Yellow Dock"},
{name: "RUMEX CRISPUS WHOLE"},
{name: "taxus"},
{name: "Linaria <Plantaginaceae>"},
{name: "lupinus"},
{name: "Cananga (DC.) Hook.f. & Thomson, 1855"},
{name: "Curcuma zedoria Root Extract"},
{name: "Zedoary"},
{name: "Yucca"},
{name: "Yucca angustifolia"},
{name: "yogurt"},
{name: "Yogurt protein"},
{name: "Zizyphus"},
{name: "Yerba Santa"},
{name: "eriodictyon californicum"},
{name: "Xylitol (product)"},
{name: "Xylitol"},
{name: "Wild Radish"},
{name: "oxalis"},
{name: "banisteriopsis"},
{name: "bacopa"},
{name: "Bacopa monnieria"},
{name: "Bayberry"},
{name: "Beta-Alanylhistidine"},
{name: "Bay leaf"},
{name: "Carob"},
{name: "Jacaranda caroba"},
{name: "Basil (dietary)"},
{name: "Basil"},
{name: "Hydrolyzed Casein"},
{name: "Casein, sodium salt"},
{name: "Casein phosphopeptide- amorphous calcium phosphate"},
{name: "Casein micelles"},
{name: "Casein"},
{name: "Peptide"},
{name: "Peptide, NOS"},
{name: "Bonito Peptide Hydrolysate"},
{name: "Glutamine peptides"},
{name: "Sesamum indicum Peptide KM-20"},
{name: "Purple Carrot"},
{name: "Carrot"},
{name: "Cinnamon"},
{name: "Cinnamonum"},
{name: "Cinnamon cassia"},
{name: "Cassia angustifolia"},
{name: "Cassia essential oil"},
{name: "cassia"},
{name: "Cassia cinnamon"},
{name: "Cassia officinalis"},
{name: "Manihot esculentas"},
{name: "Tapioca"},
{name: "Diacylglycerol"},
{name: "1, 2-Diacylglycerol"},
{name: "DIATOMACEOUS EARTH"},
{name: "Diatomaceous earth (uncalcined)"},
{name: "Cobamamide"},
{name: "Dibencozide"},
{name: "anacardium occidentale"},
{name: "Dill"},
{name: "Dill (dietary)"},
{name: "Carrageenan"},
{name: "carrageenin"},
{name: "Diosmin"},
{name: "Resin, Buchu"},
{name: "Dimethylamylamine"},
{name: "DIMETHYLAMINE"},
{name: "N,N-Dimethylglycine"},
{name: "Dimethylglycine"},
{name: "Diiodothyronines [Chemical/Ingredient]"},
{name: "Goldenrod"},
{name: "Golden Rod Extract"},
{name: "Dodder"},
{name: "cuscuta"},
{name: "Gotu Kola"},
{name: "Kola extract"},
{name: "Dolomite"},
{name: "Grape"},
{name: "Oregon Grape"},
{name: "Grains"},
{name: "Grains of Paradise"},
{name: "Paradisea"},
{name: "Convolvulus arvensis"},
{name: "Convolvulus arvensis (plant)"},
{name: "Convolvulis arvensis"},
{name: "(+/-)-Gossypol"},
{name: "Limonene"},
{name: "D-limonene"},
{name: "Tilia officinalis"},
{name: "Tilia grandifolia"},
{name: "Linden"},
{name: "Tilia Cordata"},
{name: "Tilia sylvestris"},
{name: "Tilia x vulgaris"},
{name: "Tilia (Plant)"},
{name: "Tilia argentea"},
{name: "Lingonberries"},
{name: "Greater Burnet"},
{name: "Sanguisorba officinalis"},
{name: "sanguisorba"},
{name: "adansonia"},
{name: "Baobab"},
{name: "Liver Extract"},
{name: "Lithium carbonicum"},
{name: "Lithium"},
{name: "Lithium benzoicum"},
{name: "Lithium muriaticum"},
{name: "Lithium bromatum"},
{name: "Lobelia"},
{name: "Lobelia syphilitica"},
{name: "Lobelia chinensis"},
{name: "Lobelia Inflata"},
{name: "Annona muricata"},
{name: "Graviola"},
{name: "Annona muricata (plant)"},
{name: "ANEMONE AMERICANA"},
{name: "Liverwort"},
{name: "Hepatica triloba"},
{name: "Lorenzo's oil"},
{name: "Lotus"},
{name: "Genus - Lotus"},
{name: "Loosestrife"},
{name: "LUFFA OPERCULATA WHOLE"},
{name: "Luffa operculata"},
{name: "Oil, Peanut"},
{name: "pennyroyal"},
{name: "Levisticum officinales"},
{name: "lovage"},
{name: "szechuan lovage"},
{name: "Perilla frutescens"},
{name: "perilla"},
{name: "coptis"},
{name: "Goldthread"},
{name: "Periwinkle"},
{name: "vinca"},
{name: "Shellac (substance)"},
{name: "lentinula edodes"},
{name: "Shiitake Mushroom"},
{name: "shea butter"},
{name: "PERILLYL ALCOHOL"},
{name: "(R)-4-Isopropenyl-1-methylcyclohex-1-ene"},
{name: "Peppermint essential oil"},
{name: "Peppermint"},
{name: "Peppermint leaf"},
{name: "capsella bursa pastoris"},
{name: "Shepherd's Purse"},
{name: "Thlaspi bursa-pastoris"},
{name: "red peony"},
{name: "Moutan peony"},
{name: "Peony"},
{name: "Sida cordifolia"},
{name: "Acanthopanax senticosus"},
{name: "Siberian Ginseng"},
{name: "Eleutherococcus senticosus (plant)"},
{name: "Skunk Cabbage"},
{name: "Symplocarpus, NOS"},
{name: "Silicon"},
{name: "Silicon, NOS"},
{name: "stigmastanol"},
{name: "Sitostanol"},
{name: "Morus alba"},
{name: "White Mulberry"},
{name: "Sinapis alba"},
{name: "Brassica alba"},
{name: "Xanthium sibiricum"},
{name: "Cang Er"},
{name: "White Sandalwood"},
{name: "Sandalwood"},
{name: "Red Sandalwood"},
{name: "indigo"},
{name: "Indigo Naturalis"},
{name: "Wild Indigo"},
{name: "Lettuce"},
{name: "Wild Lettuce"},
{name: "Piper nigrum (plant)"},
{name: "Weak Jumby Pepper"},
{name: "Grapefruit"},
{name: "grapefruit extract"},
{name: "Grapefruit Bioflavonoids"},
{name: "MENTHA ARVENSIS WHOLE"},
{name: "Mentha arvensis"},
{name: "Horehound"}]